networks:
  default:
    name: openfmb.demo
    driver: bridge

volumes:
  timescaledb-data:
  grafana-data:

services:
  nats:
    profiles:
      - evse
      - ui
      - save
    image: nats:2.9.25-alpine3.18
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  repeat:
    profiles:
      - evse
    image: oesinc/openfmb.adapters:v2.2.0-e829322c
    container_name: repeat
    depends_on:
      - nats
      # - timescaledb
    volumes:
      - ./repeat:/cfg
    command: -c /cfg/adapter.yaml
  replay:
    profiles:
      - ui
    image: oesinc/openfmb.adapters:a30d1d0
    container_name: replay
    depends_on:
      - nats
    volumes:
      - ./replay:/cfg
    command: -c /cfg/adapter.yaml
  save:
    profiles:
      - save
    image: oesinc/openfmb.adapters:v2.2.0-e829322c
    container_name: save
    depends_on:
      - nats
    volumes:
      - ./save:/cfg
    command: -c /cfg/adapter.yaml
  hmi:
    profiles:
      - ui
    image: oesinc/openfmb.hmi:v2.1.0
    container_name: hmi
    depends_on:
      - nats
    volumes:
      - ./hmi:/cfg
    environment:
      APP_CONF: /cfg/config/app.toml
      APP_DIR_NAME: /cfg
    ports:
      - "32771:32771"
  timescaledb:
    profiles:
      - evse
      - db
    image: timescale/timescaledb:2.18.0-pg16
    container_name: timescale-db
    ports:
      - "5434:5432"
    environment:
      # - POSTGRES_DB=openfmb
      - POSTGRES_PASSWORD=password
      # - POSTGRES_USER=openfmb-user
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    profiles:
      - evse
    image: grafana/grafana:${GRAFANA_TAG:-latest}
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
      - GF_PATHS_CONFIG=/usr/share/grafana/custom/grafana.ini
      - GF_PATHS_PROVISIONING=/usr/share/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      # Input(s):
      - ./grafana/config/custom.ini:/usr/share/grafana/custom/grafana.ini:ro
      - ./grafana/dashboards:/usr/share/grafana/dashboards:rw
      - ./grafana/provisioning:/usr/share/grafana/provisioning:rw
      # Output(s):
      - grafana-data:/var/lib/grafana   # use docker volume
