{
 "title": "DTE Chargers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Autel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT connector_state FROM public.ocpp_chargers WHERE $__timeFilter(timestamp) AND charger_name = 'Autel' ORDER BY timestamp desc limit 1"
    }
   ]
  },
  {
   "title": "Blink",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT connector_state FROM public.ocpp_chargers WHERE $__timeFilter(timestamp) AND charger_name = 'blink' ORDER BY timestamp desc limit 1"
    }
   ]
  },
  {
   "title": "OpenEvse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT connector_state FROM public.ocpp_chargers WHERE $__timeFilter(timestamp) AND charger_name = 'OpenEVSE1' ORDER BY timestamp desc limit 1"
    }
   ]
  },
  {
   "title": "Wallbox",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT connector_state FROM public.ocpp_chargers WHERE $__timeFilter(timestamp) AND charger_name = 'WB1' ORDER BY timestamp desc limit 1"
    }
   ]
  },
  {
   "title": "Siemens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT connector_state FROM public.ocpp_chargers WHERE $__timeFilter(timestamp) AND charger_name = 'SIEMENS' ORDER BY timestamp desc limit 1"
    }
   ]
  },
  {
   "title": "EVSE Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT charger_1_amps,\"timestamp\" FROM dent_meter WHERE $__timeFilter(timestamp) "
    },
    {
     "rawSql": "SELECT charger_2_amps,\"timestamp\" FROM dent_meter WHERE $__timeFilter(timestamp) "
    },
    {
     "rawSql": "SELECT charger_3_amps,\"timestamp\" FROM dent_meter WHERE $__timeFilter(timestamp) "
    },
    {
     "rawSql": "SELECT charger_4_amps,\"timestamp\" FROM dent_meter WHERE $__timeFilter(timestamp) "
    },
    {
     "rawSql": "SELECT charger_5_amps,\"timestamp\" FROM dent_meter WHERE $__timeFilter(timestamp) "
    },
    {
     "rawSql": "SELECT charger_6_amps,\"timestamp\" FROM dent_meter WHERE $__timeFilter(timestamp) "
    },
    {
     "rawSql": "SELECT charger_7_amps,\"timestamp\" FROM dent_meter WHERE $__timeFilter(timestamp) "
    }
   ]
  }
 ]
}